[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.github
)/
| foo.py           # also separately exclude a file named foo.py in
                   # the root of the project
| README_update copy.py
| README_update.py
| test_0.py
)
'''
