name: Run Tests

on:
  push:
    branches:
      - main
      - feature

env:
  GITHUB_TOKEN: ${{ secrets.ACTIONS_WORKFLOW_SECRET }}

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt

    - name: Run tests
      run: |
        # Define the log file
        log_file=unittest_log.txt

        # Clear the log file
        echo "" > $log_file

        # Loop through each folder
        for folder in src/leetcode_*
        do
            # Run the *_unittest.py script and redirect the output to the log file
            echo "Running tests in $folder" >> $log_file
            for test_file in $folder/unittest/*_unittest.py; do
              python $test_file >> $log_file
            done
            echo "" >> $log_file
        done

        # Display the log file
        cat $log_file

    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: unittest_log.txt
        path: unittest_log.txt
    
    - name: Update README
      run: |
        git pull origin ${{ github.ref }}

        # Get the current branch name
        branch=${{ github.ref }}

        # Pass the branch name to the README_update.py script
        python README_update.py $branch
    ########
    - run: |
        git pull origin ${{ github.ref }}
        git status
        git add .
        git status
        git commit -m "Update README file"

    - name: Add Commit and push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        branch:  origin ${{ github.ref }}
        message: "Update README file"
